# @package _global_
defaults:
  - /trainer: default
  - /loader: torch
  - /dataset: sc
  - /task: multiclass_classification
  - /optimizer: adamw
  - /scheduler: cosine_warmup

train:
  monitor: val/accuracy # Needed for plateau scheduler
  mode: max

encoder: linear

decoder:
  _name_: sequence
  mode: pool

dataset:
  all_classes: true

loader:
  train_resolution: 1
  eval_resolutions:
    - 1
    - 2